require("donghyun.plugins-setup")
require("donghyun.core.options")
require("donghyun.core.keymaps")
require("donghyun.core.colorscheme")
require("donghyun.plugins.comment")
require("donghyun.plugins.nvim-tree")
require("donghyun.plugins.lualine")
require("donghyun.plugins.telescope")
require("donghyun.plugins.barbar")
require("donghyun.plugins.nvim-cmp")
require("donghyun.plugins.lsp.mason")
require("donghyun.plugins.lsp.lspconfig")
-- require("donghyun.plugins.lsp.null-ls")
require("donghyun.plugins.lsp.lspsaga")
require("donghyun.plugins.autopairs")
require("donghyun.plugins.treesitter")
require("donghyun.plugins.gitsigns")
-- require("donghyun.plugins.harpoon")
require("donghyun.plugins.undotree")
require("donghyun.plugins.nvim-scrollbar")
